/*
 * This source file was generated by the Gradle 'init' task
 */
package bcc.sportsquiz;

import javax.swing.JFrame;
import javax.swing.JLabel;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        JFrame frame =new JFrame();//creating instance of JFrame  

      JLabel label =new JLabel("hello world");  
      label.setBounds(250,50, 100,30);  
      frame.add(label); 
            frame.setSize(400,400);  
            frame.setLayout(null);  
            frame.setVisible(true); 
    }
}
